Add automatic cross-reference text by id
mpark/wg21 pull request #102
Opened 2024-12-17 05:47 UTC by rarutyun

## Motivation

Usually, it's very convenient to have cross references in the document to some sections of the proposal. Markdown and Pandoc have them in a way but IMO it may be better. Let's consider the following header as an example (taken from [P3179R4](https://wg21.link/P3179R4)):

```md
## Algorithm return types ## {#return_type}
```
If we would like to refer to this title (with the text as-is) in the document I found two ways (except html): 
- With Markdown: `[Algorithm return types](#return_type)`. While it works, it seems to much to me because all the necessary information already exists and it should be sufficient to write an id and fill the text automatically for me.
- With Pandoc: `[Algorithm return types]`. It's, IMO, better but not quite because from my experience one changes the text more often compared to changing ids.

In [P3179R4](https://wg21.link/P3179R4) we have a lot of cross-references and now we are preparing [P3179R5](https://github.com/rarutyun/iso_cpp_papers/pull/17) with moving away from **bikeshed** towards **mpark-wg21**. It would be super nice to have automatic text for cross-references.

## Competitive frameworks

**bikeshed** does support this functionality with the following syntax `[[#return_type]]`. Basically, this syntax is used for both cross-references and references from biblio (like `[[P3179R3]]`).

## Proposed syntax

There is no concrete proposed syntax. The way how it's implemented right now is `[](#return_type)` meaning that if the text for the link is empty and the link starts from `#` wg21.py should use the automatic text from title (in our case the text should be 'Algorithm return types')

We might consider alternative syntax, which I believe is implementable: `[#return_type]{.cref}` where `cref` means cross-reference. Maybe this syntax is preferable because in case of a typo in the id the document would show unrendered link instead of nothing.

Anyway, I am ready to discuss the syntax.

2024-12-17 05:47 UTC, rarutyun commented
Hey @mpark, could you please review?

@akukanov, FYI

2024-12-17 20:22 UTC, akukanov commented
Another syntax idea is `[@#id]`, e.g. `[@#return-type]` in @rarutyun's example. It's a bit more concise, and similar to the `[@PxxxxRn]` syntax for "citations"/biblio references. I have not thought of feasibility for it, though.

2024-12-18 05:50 UTC, mpark commented
Thanks for raising this. I do agree with the motivation. It looks like there is a pending Pandoc issue https://github.com/jgm/pandoc/issues/6091 for something similar, but it hasn't made progress since 2020. I actually think the suggested syntax in your PR is reasonable, i.e. `[](#header-id)`. I'll review the actual implementation shortly.

2024-12-18 12:18 UTC, akukanov commented
Another thought on the syntax, in order to address this:
> in case of a typo in the id the document would show unrendered link instead of nothing.

Perhaps `@` can be used as the "placeholder" to substitute with the actual name, i.e. `[@](#header-id)`. In the case of a typo, either the symbol be rendered directly or perhaps replaced with `#header-id`.

Well, of course rendering the unresolved id as the text can be implemented for the empty brackets as well.

2025-01-02 05:51 UTC, mpark requested changes
Looks good overall. Please consider the suggestions made here, and I'll approve the result! Do you mind adding this to the `README.md` and a test case to `TEST.md` as well please?

2025-01-02 05:51 UTC, mpark commented on data/filters/wg21.py
> +self_links = {}
```suggestion
headers = {}
```

2025-01-02 05:51 UTC, mpark commented on data/filters/wg21.py
> +    string_url = f'#{elem.identifier}'
```suggestion
    url = f'#{elem.identifier}'
```

2025-01-02 05:51 UTC, mpark commented on data/filters/wg21.py
> +    elem.content.append(self_link)
No need to pull out `self_link` here.
```suggestion
    elem.content.append(pf.Link(url=url, classes=['self-link']))
```

2025-01-02 05:51 UTC, mpark commented on data/filters/wg21.py
> +    return elem
```suggestion
    if (header_text := headers.get(elem.url)) is not None:
        return pf.Link(pf.Str(header_text), url=elem.url)
    
    pf.debug('mpark/wg21: cannot find automatic text for cross-reference for:', elem.url)
    return None
```

2025-01-02 05:51 UTC, mpark commented on data/filters/wg21.py
> +    if not isinstance(elem, pf.Link) or ('self-link' in elem.classes) or not (elem.url.startswith('#')):
I tend to prefer doing `if not (conditions ...)` for filter conditions like this, and the `link_text` condition can go in here as well:
```suggestion
    if not (isinstance(elem, pf.Link) and
            elem.url.startswith('#') and
            ('self-link' not in elem.classes) and
            pf.stringify(elem) == ""):
         return None
```

2025-01-07 02:26 UTC, mpark commented
I just discovered that this bit me recently as well in one of my [own papers](https://isocpp.org/files/papers/P2688R4.html#syntax-overview):

```
See [7.6.4+1 Pattern matching operator [expr.match]] for the formal grammar.
```

I changed the header to `7.6.4+1 [expr.match] Pattern matching expression`,
so the link was broken but there was no indication. Referring to an ID here would've
been more stable.

2025-01-09 02:28 UTC, rarutyun commented on data/filters/wg21.py
> +self_links = {}
Done

2025-01-09 02:28 UTC, rarutyun commented on data/filters/wg21.py
> +    elem.content.append(self_link)
Done

2025-01-09 02:28 UTC, rarutyun commented on data/filters/wg21.py
> +    string_url = f'#{elem.identifier}'
Done

2025-01-09 02:29 UTC, rarutyun commented on data/filters/wg21.py
> +    if not isinstance(elem, pf.Link) or ('self-link' in elem.classes) or not (elem.url.startswith('#')):
I am not a big fun of it in this very case because we use double negation for `self-link`. But it's a slight preference, so I applied the comment as you suggested

2025-01-09 07:42 UTC, mpark commented on data/filters/wg21.py
> +    return elem
Sure, looks fine to me!

2025-01-09 08:31 UTC, mpark requested changes
The implementation looks good to me. The suggestions are only for the `README.md` and `TEST.md`.

2025-01-09 08:31 UTC, mpark commented on README.md
> +For example, if your source code has a header like `# Algorithm Return Type # {#return_type}`,
```suggestion
For example, if your source code has a header like `# Algorithm Return Type {#return-type}`,
```

2025-01-09 08:31 UTC, mpark commented on TEST.md
> +# Automatic Cross-References # {#auto-cross-ref}
```suggestion
# Automatic Header Links {#auto-header-links}
```

2025-01-09 08:31 UTC, mpark commented on TEST.md
> +  - `[](#auto-cross-ref)` → [](#auto-cross-ref)
The reason you were getting the red highlighting here is because inline code in the framework is highlighted as `cpp` by default. I guess the `` `[foo]{.cls}` `` above gets highlighted as `cpp` nicely enough, but `` `[foo](#id)` `` isn't working, so in this case we need to do `` `[foo](#id)`{.markdown} ``
```suggestion
Automatic header links are written as `[](#auto-header-links)`{.markdown}, and renders as [](#auto-header-links).
```

2025-01-09 08:31 UTC, mpark commented on README.md
> +  - [Automatic Cross-References](#automatic-cross-references)
```suggestion
  - [Automatic Header Links](#automatic-header-links)
```
and maybe move this above like:
```
- [Markdown](#markdown)
  - [Automatic Header Links](#automatic-header-links)
```

2025-01-09 08:31 UTC, mpark commented on README.md
> +you can reference it using `[](#return_type)`. The rendered document will automatically display
```suggestion
you can reference it using `[](#return-type)`. The rendered document will automatically display
```

2025-01-09 08:31 UTC, mpark commented on README.md
> +'Algorithm Return Type' as the cross-reference text.
```suggestion
"Algorithm Return Type" as the link text.
```

2025-01-09 08:31 UTC, mpark commented on README.md
> +`[](#header-id)`
you may omit the link text like this: `[](#header-id)`

2025-01-09 08:31 UTC, mpark commented on README.md
> +  the same type as the corresponding serial range algorithms. See [](#return_type).
```suggestion
  the same type as the corresponding serial range algorithms. See [](#return-type).
```

2025-01-09 08:31 UTC, mpark commented on data/filters/wg21.py
> +def automatic_cross_reference_text(elem, doc):
```suggestion
def automatic_header_link(elem, doc):
```

2025-01-09 08:31 UTC, mpark commented on data/filters/wg21.py
> +        pf.debug('mpark/wg21: cannot find automatic text for cross-reference for:', elem.url)
```suggestion
        pf.debug('mpark/wg21: cannot find automatic text for link to:', elem.url)
```

2025-01-09 08:31 UTC, mpark commented on data/filters/wg21.py
> +      automatic_cross_reference_text,
```suggestion
      automatic_header_link,
```

2025-01-10 00:33 UTC, rarutyun commented on README.md
> +  - [Automatic Cross-References](#automatic-cross-references)
Done

2025-01-10 00:33 UTC, rarutyun commented on README.md
> +#### Automatic Cross-References
Moved. The modification is also done.

2025-01-10 00:33 UTC, rarutyun commented on README.md
> +To refer to a header by its ID and have the cross-reference text automatically extracted,
Done

2025-01-10 00:33 UTC, rarutyun commented on README.md
> +`[](#header-id)`
Done

2025-01-10 00:33 UTC, rarutyun commented on README.md
> +For example, if your source code has a header like `# Algorithm Return Type # {#return_type}`,
Done

2025-01-10 00:33 UTC, rarutyun commented on README.md
> +you can reference it using `[](#return_type)`. The rendered document will automatically display
Done.

2025-01-10 00:33 UTC, rarutyun commented on README.md
> +  the same type as the corresponding serial range algorithms. See [](#return_type).
Done

2025-01-10 00:33 UTC, rarutyun commented on README.md
> +'Algorithm Return Type' as the cross-reference text.
Done

2025-01-10 00:33 UTC, rarutyun commented on TEST.md
> +# Automatic Cross-References # {#auto-cross-ref}
Done

2025-01-10 00:33 UTC, rarutyun commented on data/filters/wg21.py
> +def automatic_cross_reference_text(elem, doc):
Done

2025-01-10 00:33 UTC, rarutyun commented on data/filters/wg21.py
> +        pf.debug('mpark/wg21: cannot find automatic text for cross-reference for:', elem.url)
Done

2025-01-10 00:33 UTC, rarutyun commented on data/filters/wg21.py
> +      automatic_cross_reference_text,
Done

2025-01-10 00:36 UTC, rarutyun commented on TEST.md
> +  - `[](#auto-cross-ref)` → [](#auto-cross-ref)
Done

2025-01-10 00:53 UTC, mpark approved these changes

2025-01-10 00:54 UTC, merged